name: publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          IMAGE=ghcr.io/mortennordbye/weasyprint
          GIT_SHA=${GITHUB_SHA::7}

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE:latest \
            -t $IMAGE:$GIT_SHA \
            --push .

